// GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.
// Design-system barrel: every component module this repo ships.

export * from "../src/components/BottomSheet";
export * from "../src/components/PoolPickerSheet";
export * from "../src/components/SpeakButton";
export * from "../src/components/TabBar";
export * from "../src/components/VocabList";
export * from "../src/components/classes/Reference";
export * from "../src/components/exercises/GradeButtons";
export * from "../src/components/lexicon/CardsTab";
export * from "../src/components/lexicon/PoolTab";
export * from "../src/components/ui/accordion";
export * from "../src/components/ui/alert-dialog";
export * from "../src/components/ui/alert";
export * from "../src/components/ui/aspect-ratio";
export * from "../src/components/ui/avatar";
export * from "../src/components/ui/badge";
export * from "../src/components/ui/breadcrumb";
export * from "../src/components/ui/button";
export * from "../src/components/ui/calendar";
export * from "../src/components/ui/card";
export * from "../src/components/ui/carousel";
export * from "../src/components/ui/chart";
export * from "../src/components/ui/checkbox";
export * from "../src/components/ui/collapsible";
export * from "../src/components/ui/command";
export * from "../src/components/ui/context-menu";
export * from "../src/components/ui/dialog";
export * from "../src/components/ui/drawer";
export * from "../src/components/ui/dropdown-menu";
export * from "../src/components/ui/form";
export * from "../src/components/ui/hover-card";
export * from "../src/components/ui/input-otp";
export * from "../src/components/ui/input";
export * from "../src/components/ui/label";
export * from "../src/components/ui/menubar";
export * from "../src/components/ui/navigation-menu";
export * from "../src/components/ui/pagination";
export * from "../src/components/ui/popover";
export * from "../src/components/ui/progress";
export * from "../src/components/ui/radio-group";
export * from "../src/components/ui/resizable";
export * from "../src/components/ui/scroll-area";
export * from "../src/components/ui/select";
export * from "../src/components/ui/separator";
export * from "../src/components/ui/sheet";
export * from "../src/components/ui/sidebar";
export * from "../src/components/ui/skeleton";
export * from "../src/components/ui/slider";
export * from "../src/components/ui/sonner";
export * from "../src/components/ui/switch";
export * from "../src/components/ui/table";
export * from "../src/components/ui/tabs";
export * from "../src/components/ui/textarea";
export * from "../src/components/ui/toggle-group";
export * from "../src/components/ui/toggle";
export * from "../src/components/ui/tooltip";

// sonner's imperative API. `Toaster` only renders toasts pushed through the
// same sonner instance, so it has to come out of this bundle too — a consumer
// importing "sonner" separately gets a second store and sees nothing. The app
// itself uses it this way (PoolPickerSheet, PoolTab, account, lib/pwa).
export { toast } from "sonner";

// Router + query context for preview cards. Must ship from this bundle so it
// shares module instances with the components — see preview-providers.tsx.
export { DsPreviewProviders } from "./preview-providers";
