/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrainerRouteImport } from './routes/_authenticated/trainer'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedLexiconRouteImport } from './routes/_authenticated/lexicon'
import { Route as AuthenticatedDialoguesRouteImport } from './routes/_authenticated/dialogues'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWordsTodayRouteImport } from './routes/_authenticated/words.today'
import { Route as AuthenticatedWordsMasteredRouteImport } from './routes/_authenticated/words.mastered'
import { Route as AuthenticatedLexiconNewRouteImport } from './routes/_authenticated/lexicon_.new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainerRoute = AuthenticatedTrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLexiconRoute = AuthenticatedLexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDialoguesRoute = AuthenticatedDialoguesRouteImport.update({
  id: '/dialogues',
  path: '/dialogues',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWordsTodayRoute = AuthenticatedWordsTodayRouteImport.update({
  id: '/words/today',
  path: '/words/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWordsMasteredRoute =
  AuthenticatedWordsMasteredRouteImport.update({
    id: '/words/mastered',
    path: '/words/mastered',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLexiconNewRoute = AuthenticatedLexiconNewRouteImport.update({
  id: '/lexicon_/new',
  path: '/lexicon/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/account': typeof AuthenticatedAccountRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dialogues': typeof AuthenticatedDialoguesRoute
  '/lexicon': typeof AuthenticatedLexiconRoute
  '/review': typeof AuthenticatedReviewRoute
  '/trainer': typeof AuthenticatedTrainerRoute
  '/lexicon/new': typeof AuthenticatedLexiconNewRoute
  '/words/mastered': typeof AuthenticatedWordsMasteredRoute
  '/words/today': typeof AuthenticatedWordsTodayRoute
}
export interface FileRoutesByTo {
  '/account': typeof AuthenticatedAccountRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dialogues': typeof AuthenticatedDialoguesRoute
  '/lexicon': typeof AuthenticatedLexiconRoute
  '/review': typeof AuthenticatedReviewRoute
  '/trainer': typeof AuthenticatedTrainerRoute
  '/': typeof AuthenticatedIndexRoute
  '/lexicon/new': typeof AuthenticatedLexiconNewRoute
  '/words/mastered': typeof AuthenticatedWordsMasteredRoute
  '/words/today': typeof AuthenticatedWordsTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dialogues': typeof AuthenticatedDialoguesRoute
  '/_authenticated/lexicon': typeof AuthenticatedLexiconRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/trainer': typeof AuthenticatedTrainerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/lexicon_/new': typeof AuthenticatedLexiconNewRoute
  '/_authenticated/words/mastered': typeof AuthenticatedWordsMasteredRoute
  '/_authenticated/words/today': typeof AuthenticatedWordsTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/classes'
    | '/dialogues'
    | '/lexicon'
    | '/review'
    | '/trainer'
    | '/lexicon/new'
    | '/words/mastered'
    | '/words/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/classes'
    | '/dialogues'
    | '/lexicon'
    | '/review'
    | '/trainer'
    | '/'
    | '/lexicon/new'
    | '/words/mastered'
    | '/words/today'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/account'
    | '/_authenticated/classes'
    | '/_authenticated/dialogues'
    | '/_authenticated/lexicon'
    | '/_authenticated/review'
    | '/_authenticated/trainer'
    | '/_authenticated/'
    | '/_authenticated/lexicon_/new'
    | '/_authenticated/words/mastered'
    | '/_authenticated/words/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trainer': {
      id: '/_authenticated/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof AuthenticatedTrainerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lexicon': {
      id: '/_authenticated/lexicon'
      path: '/lexicon'
      fullPath: '/lexicon'
      preLoaderRoute: typeof AuthenticatedLexiconRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dialogues': {
      id: '/_authenticated/dialogues'
      path: '/dialogues'
      fullPath: '/dialogues'
      preLoaderRoute: typeof AuthenticatedDialoguesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/words/today': {
      id: '/_authenticated/words/today'
      path: '/words/today'
      fullPath: '/words/today'
      preLoaderRoute: typeof AuthenticatedWordsTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/words/mastered': {
      id: '/_authenticated/words/mastered'
      path: '/words/mastered'
      fullPath: '/words/mastered'
      preLoaderRoute: typeof AuthenticatedWordsMasteredRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lexicon_/new': {
      id: '/_authenticated/lexicon_/new'
      path: '/lexicon/new'
      fullPath: '/lexicon/new'
      preLoaderRoute: typeof AuthenticatedLexiconNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDialoguesRoute: typeof AuthenticatedDialoguesRoute
  AuthenticatedLexiconRoute: typeof AuthenticatedLexiconRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedTrainerRoute: typeof AuthenticatedTrainerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLexiconNewRoute: typeof AuthenticatedLexiconNewRoute
  AuthenticatedWordsMasteredRoute: typeof AuthenticatedWordsMasteredRoute
  AuthenticatedWordsTodayRoute: typeof AuthenticatedWordsTodayRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDialoguesRoute: AuthenticatedDialoguesRoute,
  AuthenticatedLexiconRoute: AuthenticatedLexiconRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedTrainerRoute: AuthenticatedTrainerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLexiconNewRoute: AuthenticatedLexiconNewRoute,
  AuthenticatedWordsMasteredRoute: AuthenticatedWordsMasteredRoute,
  AuthenticatedWordsTodayRoute: AuthenticatedWordsTodayRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
